server:
  #  ssl:
  #      key-store-type: PKCS12
  #      key-store: classpath:keystore.p12
  #      key-store-password: xdwxdw123
  #      key-alias: tomcat
  port: 5000
spring:
  datasource:
#    url: jdbc:oracle:thin:@192.168.0.25:1521:odb12
    url: jdbc:oracle:thin:@172.16.0.105:1521:odb12
    username: XXI
    password: NEW8I
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-init-sql: SELECT 1 from dual
      connection-test-query: SELECT 1 from dual
      auto-commit: true
      connection-timeout: 120000
      idle-timeout: 600000
      leak-detection-threshold: 60000
      max-lifetime: 1800000
      maximum-pool-size: 10
      validation-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true

logging:
  file:
    name: rtgslog.log
#  level:
#    com.zaxxer.hikari.pool.HikariPool: DEBUG

ProjectProperties:
  expiresIn: 3600
  secretKey: success
